/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazParcial;

/**
 *
 * @author Usuario
 */
public class GUIResultados extends javax.swing.JFrame {

    /**
     * Creates new form GUIResultados
     */
    public GUIResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbChina = new javax.swing.JLabel();
        lbEspaña = new javax.swing.JLabel();
        lbItalia = new javax.swing.JLabel();
        lbFrancia = new javax.swing.JLabel();
        lbEEUU = new javax.swing.JLabel();
        lbOtros = new javax.swing.JLabel();
        OTROS = new javax.swing.JLabel();
        china = new javax.swing.JLabel();
        Espania = new javax.swing.JLabel();
        italia = new javax.swing.JLabel();
        francia = new javax.swing.JLabel();
        EEUU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lbChina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbChina.setText("China :");
        getContentPane().add(lbChina);
        lbChina.setBounds(70, 50, 48, 17);

        lbEspaña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEspaña.setText("España :");
        getContentPane().add(lbEspaña);
        lbEspaña.setBounds(70, 80, 59, 17);

        lbItalia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbItalia.setText("Italia :");
        getContentPane().add(lbItalia);
        lbItalia.setBounds(70, 110, 44, 17);

        lbFrancia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFrancia.setText("Francia:");
        getContentPane().add(lbFrancia);
        lbFrancia.setBounds(70, 140, 54, 17);

        lbEEUU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbEEUU.setText("EE.UU:");
        getContentPane().add(lbEEUU);
        lbEEUU.setBounds(70, 170, 47, 17);

        lbOtros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbOtros.setText("Otros:");
        getContentPane().add(lbOtros);
        lbOtros.setBounds(70, 200, 44, 17);

        OTROS.setText("0");
        getContentPane().add(OTROS);
        OTROS.setBounds(180, 194, 40, 20);

        china.setText("0");
        getContentPane().add(china);
        china.setBounds(180, 50, 30, 20);
        china.getAccessibleContext().setAccessibleName("lbNumChi");

        Espania.setText("0");
        getContentPane().add(Espania);
        Espania.setBounds(180, 80, 40, 20);
        Espania.getAccessibleContext().setAccessibleName("lbNumEsp");

        italia.setText("0");
        getContentPane().add(italia);
        italia.setBounds(180, 110, 40, 20);

        francia.setText("0");
        getContentPane().add(francia);
        francia.setBounds(180, 140, 30, 20);

        EEUU.setText("0");
        getContentPane().add(EEUU);
        EEUU.setBounds(180, 164, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel EEUU;
    public javax.swing.JLabel Espania;
    public javax.swing.JLabel OTROS;
    public javax.swing.JLabel china;
    public javax.swing.JLabel francia;
    public javax.swing.JLabel italia;
    private javax.swing.JLabel lbChina;
    private javax.swing.JLabel lbEEUU;
    private javax.swing.JLabel lbEspaña;
    private javax.swing.JLabel lbFrancia;
    private javax.swing.JLabel lbItalia;
    private javax.swing.JLabel lbOtros;
    // End of variables declaration//GEN-END:variables
}
