/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazParcial;

/**
 *
 * @author Usuario
 */
public class GUIRecomendaciones extends javax.swing.JFrame {

    /**
     * Creates new form GUIRecomendaciones
     */
    public GUIRecomendaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRecomendaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRecomendaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRecomendaciones.setText("Recomendaciones");
        getContentPane().add(lbRecomendaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazParcial/Captura.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 640, 590));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Si tiene algunos de los sintomas anteriores, por favor llame inmediatamente al 123.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbRecomendaciones;
    // End of variables declaration//GEN-END:variables
}
